### ISSUE TITLE
Different actionname than Index

### ISSUE THREAD

**Issue by michaelkovarik** [sonnemaf/ReflectionIT.Mvc.Paging#12]
Hello,

your nuget extension is great !

But, i have only one but very very important knowledge.

The paging system is possible to do only in Index actions of controller, paging is working, but links to next pages are without action name .. For example - i am on this route: "localhost/controller/products?page=2"

and if i will click on page 3 button, its link is "localhost/controller?page=3"

Is possible to improve your extension ?

Thank youuu !

**Comment by sonnemaf** [comment]
Hi,  
This is already possible. You can set the Action property to of the PagingList<T> object.  
Regards,  
Fons

**Comment by michaelkovarik** [comment]
Aah, thank you :)
I was meaning about "Create" method with new parameter for action name, so i added to project this:

```
`public static PagingList<T> Create<T>(IEnumerable<T> qry, int pageSize, int pageIndex,string action) where T : class {
            var totalRecordCount = qry.Count();
            var pageCount = (int)Math.Ceiling(totalRecordCount / (double)pageSize);

            return new PagingList<T>(qry.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList(), pageSize, pageIndex, pageCount, totalRecordCount, action);
        }`

and 

internal PagingList(List<T> list, int pageSize, int pageIndex, int pageCount, int totalRecordCount, string action)
            : base(list) {
            this.TotalRecordCount = totalRecordCount;
            this.PageIndex = pageIndex;
            this.PageCount = pageCount;
            this.Action = action;
            this.PageParameterName = "page";
            this.SortExpressionParameterName = "sortExpression";
        }
```

Maybe someone will use it.

Anyway, thank you :)
