### ISSUE TITLE
Html.SortableHeaderFor link pointing to other page

### ISSUE THREAD

**Issue by saifalmaluk** [sonnemaf/ReflectionIT.Mvc.Paging#17]
We have created mvc page List.cshtml

A table with clickable header is like below,

 ` @Html.SortableHeaderFor(model => model.Title, this.Model)`

The issue is when we click on header, it redirecting to index.cshtml page instead of list.cshtml.

**Comment by Moxh3** [comment]
Same issue here, I'm routing to a specific page (non-index), but SortableHeaderFor provides links to the index...

**Comment by Moxh3** [comment]
Fixed it myself. You can set the Action to route to:
`list.Action = "Rifle";`

where `list` is an instance of PagingList<T>
