### ISSUE TITLE
Pagination links not working because PagingListOfT.PageParameterName is set to 'page' which is a reserved route name.

### ISSUE THREAD

**Issue by mvsantos013** [sonnemaf/ReflectionIT.Mvc.Paging#21]
There is more context on this [question](https://stackoverflow.com/questions/55049852/actionlink-generating-empty-href-when-using-url-get-parameter-named-page) I submitted on StackOverflow. Right now the code is using a [reserved route name called 'page'](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#reserved-routing-names), it doesn't work when the app has Identity features.

Here's a solution: change PagingListOfT.PageParameterName default name.

Additional: Insert in PagingOptions a 'public string PageLinkUrlGetName { get; set; } = "bookpage";' option.

**Comment by sonnemaf** [comment]
This would be a breaking change, old code won't work any more. We must search for a solution for that.

**Comment by sonnemaf** [comment]
Added a PageParameterName to the PagingOptions. You can set this to for example pageIndex. Make sure you also rename the parameters of your Actions.

```
services.AddPaging(options => {
    options.ViewName = "Bootstrap4"
    options.PageParameterName = "pageindex";
});
```

**Comment by coommark** [comment]
I am leaving this comment for anyone else who might encounter an issue similar to mine. In the documentation, it mentions a fix for applications with Areas. In my specific instance, my application is Multitenant, and also uses Areas. Thus the routes are something like this: `https://localhost:44364/Tenant/Area/Users`. 

None of the fixes mentioned here worked for me. The workaround for me was, instead of using:

```
<nav aria-label="Suppliers navigation example">
    <vc:pager paging-list="@Model" />
</nav>
```

I used the snippet below (taken from the [original post](https://reflectionit.nl/blog/2017/paging-in-asp-net-core-mvc-and-entityframework-core)), and that worked!:

```
<nav aria-label="Suppliers navigation example">
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>
```

Thank you for this package.

**Comment by ribeiro-dev** [comment]
> I am leaving this comment for anyone else who might encounter an issue similar to mine. In the documentation, it mentions a fix for applications with Areas. In my specific instance, my application is Multitenant, and also uses Areas. Thus the routes are something like this: `https://localhost:44364/Tenant/Area/Users`.
> 
> None of the fixes mentioned here worked for me. The workaround for me was, instead of using:
> 
> ```
> <nav aria-label="Suppliers navigation example">
>     <vc:pager paging-list="@Model" />
> </nav>
> ```
> 
> I used the snippet below (taken from the [original post](https://reflectionit.nl/blog/2017/paging-in-asp-net-core-mvc-and-entityframework-core)), and that worked!:
> 
> ```
> <nav aria-label="Suppliers navigation example">
>     @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
> </nav>
> ```
> 
> Thank you for this package.

Same here. 
You saved me, thanks!
