### ISSUE TITLE
ReflectionIT.MVC.Paging supported in .net core 3.0

### ISSUE THREAD

**Issue by esmeraldahs** [sonnemaf/ReflectionIT.Mvc.Paging#28]
Hello,
I upgraded my solution from .net core 2.2 to .net core 3.0
After upgrading i am getting this error:
Reference to type 'RouteValueDictionary' claims it is defined in 'Microsoft.AspNetCore.Routing.Abstractions', but it could not be found.

![image](https://user-images.githubusercontent.com/19766388/68467183-0a166f80-0216-11ea-93ab-c54e3c45cecd.png)

I am stuck and i am not sure if it's compatibility problem between ReflectionIT.MVC.Paging and .net core 3.0 or any other package is messed? 

Any help is appreciated, thank you!

**Comment by sonnemaf** [comment]
Which version of our NuGet package are you using. It should be 4.0.0 
https://www.nuget.org/packages/ReflectionIT.Mvc.Paging/4.0.0

**Comment by esmeraldahs** [comment]
Yes, now im using version 4.0.0 but it was recently updated (3 or 4 days ago). Thank you :)
