### ISSUE TITLE
Is not posible use a generic IQueryable

### ISSUE THREAD

**Issue by Koronos** [sonnemaf/ReflectionIT.Mvc.Paging#3]
I am trying to use `PagingList.CreateAsync` whit a generic IQueryable, and I get the next error:

```c#
System.InvalidOperationException: The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IEntityQueryProvider can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ReflectionIT.Mvc.Paging.PagingList.<CreateAsync>d__1`1.MoveNext()
```

The problem is that I use the pagination whit a `List<T>` because the UserManager (Identity) returns this when you try to get the users by role:

```c#
var qry = await _userManager.GetUsersInRoleAsync("administrator"); //Returns a List,
``` 

And if I try to use `AsQueryable()`, I get the previous error.

There is 2 posibilites. Make `PagingList` works whit `List` or change something to an Generic IQueryable works. This will give more flexibility to the use.

PD: I'm new in C# Development and in GitHub... I don't know how exactly make this changes by myself, any help to adapt the code/library is welcome.

**Comment by sonnemaf** [comment]
Thank you for reporting this problem. I will dig into the problem, probably next week.

**Comment by Koronos** [comment]
@sonnemaf I did a pull request #4 solving this issue, but maybe there is a better solution. Currently I am using a version with this fix and it don't have any problem, check it please.

**Comment by sonnemaf** [comment]
I have added IEnumerable<T> support to the main branch by adding PagingList.Create(IEnumerable source) methods (2 overloads). You can get it using the NuGet package 2.1.0. There is also a DemoController added to the sample project which uses this feature. I hope this works for you.
