### ISSUE TITLE
i can use only index in controller. i want to use at another method (like product list)

### ISSUE THREAD

**Issue by sercaneryaz** [sonnemaf/ReflectionIT.Mvc.Paging#36]
when im trying to use at another page listing. i cant use paging. it says Index not found. how can i set option to depend on controller method

**Comment by TheeDouglasAM3** [comment]
You can add a value in the property Action of model PagingList<Yourmodel>, so if you want to paginate the products in the method ProductsList of your Controller, you can use:

var model =PagingList.Create(qry, 5, page);
model.Action = "ProductsList";
