### ISSUE TITLE
I dont work pager with bootstrap

### ISSUE THREAD

**Issue by sak1065** [sonnemaf/ReflectionIT.Mvc.Paging#38]
Hello, what should be the use of paged data from an existing webapi

**Comment by sonnemaf** [comment]
This solution is not designed to support WebApi only LINQ/EntityFramework.

**Comment by sak1065** [comment]
yes, i understand then changed your created code. i had sent totalcountpage parameter  manuel and then changed create class "skip|| take " delete only return tolist. 

my english not good :)
