### ISSUE TITLE
Page Links are not working

### ISSUE THREAD

**Issue by mujibhalimi** [sonnemaf/ReflectionIT.Mvc.Paging#48]
<nav aria-label="Products navigation example">
    <vc:pager paging-list="@Model"></vc:pager>
</nav>

I am using SQL server 2008 with Asp.net Core 3.1, the problem is in the above nave tag, at the URL while using query string it's working properly like http://localhost:15562/all-students?pageindex=2 it's showing the second-page records. but buttons are not working it's showing the pagination number but doesn't perform any action. reloading the same page while clicking on each number button.

**Comment by sonnemaf** [comment]
Hi,

With only this info I can't help you. Can you publish your code in a repository so I can have a look?

Regards,

Fons

**Comment by mujibhalimi** [comment]
Thanks solved , I wrote instead of pagingList pagList.
